package kafka.topics


import utils.StringUtils

enum TopicName {

    ADD_INTEREST_DISCOUNT,
    APPLY_COURT_DECISION,
    APPLY_FIXED_AMOUNT_DISCOUNT,
    BANKRUPT_CUSTOMER,
    BILLING_RECEIVED_PAYMENT,
    CANCEL_COMMISSION,
    CANCEL_FREEZING,
    CANCEL_FUNDS_RESERVATION,
    CANCEL_LOAN_AGREEMENT,
    CLOSE_BAD_LOAN,
    CLOSE_LOAN_WITH_DISCOUNT,
    CUSTOMER_CANCELLED_REFINANCE_INTENT,
    CUSTOMER_CANCELED_PAYMENT,
    CUSTOMER_PROMISED_REFINANCE,
    CUSTOMER_RECEIVED_MONEY,
    CUSTOMER_REQUESTED_COMMISSION,
    CUSTOMER_REQUESTED_FREEZING,
    CUSTOMER_SIGNED_PROLONGATION,
    CUSTOMER_MADE_PAYMENT,
    INTEREST_DISCOUNT_CANCELED,
    LOAN_UPDATED,
    LOAN_AGREEMENT_CANCELED,
    LOAN_SOLD,
    LOAN_WRITTEN_OFF,
    PAY_LOAN_FROM_BALANCE,
    PROLONG_FREEZING,
    RESERVE_FUNDS_ON_BALANCE,
    RESUME_LOAN_CALCULATION,
    STOP_LOAN,
    STOP_LOANS_BY_BANKRUPT_CUSTOMER,
    STOP_LOANS_BY_FRAUD_CUSTOMER,
    WITHDRAW_FUNDS_FROM_BALANCE,
    CUSTOMER_PAID_COMMISSION,

    BILLING_ERRORS,
    MSG_PROCESSING_ERROR,

    TARIFF_GRID_UPDATED


    String toCamelCase() {
        if (name() == "BILLING_ERRORS") {
            return "billing-errors"
        }
        return StringUtils.snakeCaseToCamelCase(name())
    }
}